### ISSUE TITLE
A question about constructing training dataset with abnormal sample.

### ISSUE THREAD

**Issue by FiresWorker** [svip-lab/MLEP#6]
In the code, you add parts of the test data to the train data. The new train data is "train_val_clips_dict".

In the "train_val_clips_dict", we have "normal"  and "abnormal". 

In the "abnormal", each frame is belong to abnormal.

And I have a question about the "normal".

># check is normal or abnormal
>if len(frame_mask) != 0 and np.count_nonzero(frame_mask[start : end : t]) >= at_least_anomalies:
>   video_abnormal_clips.append(video_clips)
>    video_abnormal_clips.append(reversed_video_clips)
>else:
>    video_normal_clips.append(video_clips)
>    video_normal_clips.append(reversed_video_clips)

Some "video_clips" (five time steps) with one or two abnormal sample also belong to the "normal". This make me doubt.

Why we make these "video_clips" belong to "normal".

**Comment by StevenLiuWen** [comment]
Hi @FiresWorker, it depends on the criteria to classify a video clip with T frames (five frames in codes) being normal or abnormal. We assume that a video clip is normal if more than half of the frames are normal. The strictest criteria are that all frames must be normal.

**Comment by FiresWorker** [comment]
Thank you for replying to my question. ^_^
